microsoft/ApplicationInsights-dotnet-logging

- CHANGELOG.md
- src/Adapters.Tests/Log4NetAppender.Tests.Shared/ApplicationInsightsAppenderTests.cs
- src/Adapters.Tests/NLogTarget.Tests.Shared/NLogTargetTests.cs
- src/Adapters/Log4NetAppender.Shared/ApplicationInsightsAppender.cs
- src/Adapters/NLogTarget.Shared/ApplicationInsightsTarget.cs
To resolve #28 : in this version we will add custom trace message to custom properties.
After we update to Core SDK 2.2 we can switch: add exception message in custom properties and trace message use as main exception telemetry message. (To allow this there was a change in Core SDK: https://github.com/Microsoft/ApplicationInsights-dotnet/pull/242 )
> Add trace message to custom properties #28

- src/Adapters.Tests/Etw.Net451.Tests/Etw.Net451.Tests.csproj
- src/Adapters.Tests/Etw.Net451.Tests/EtwTelemetryModuleTests.cs
- src/Adapters.Tests/Etw.Net451.Tests/TraceEventSessionMock.cs
- src/Adapters.Tests/Shared/CustomTelemetryChannel.cs
- src/Adapters/Etw.Net451/AITraceEventSession.cs
- src/Adapters/Etw.Net451/EtwTelemetryModule.cs
- src/Adapters/Etw.Net451/ITraceEventSession.cs
The tests passed on the local debugging session but failed during
running. There are 2 issues contribute to the failure on the sever.
1. Initialize() will return slightly earlier than
traceEventSession.Process() is fully running. Which leads to the event
lost for the unit test because the unit test invokes the event
immediately after calling the initilize() on the module.
Although the right fix would be locking on initilize() until Process()
is fully up, it is an overhead to implement. At the same time, in real
world scenario, events are emitted in different process and will be
capatured once Process() is up.
So, I am fixing the issue by simple put a delay in the unit test after
calling initialize().
2. When using F5 (Debug) to invoke unit tests and break the test case in
the middle, the …
> Fix unit tests failure due to racing condition

- NuGet.Config
This should hopefully fix the restore issue we have seen with the last build attempt
> Add dotnet MyGet package source

- src/Adapters.Tests/Etw.Net451.Tests/EtwTelemetryModuleTests.cs
- src/Adapters.Tests/Etw.Net451.Tests/TestProvider.cs
- src/Adapters.Tests/EventSource.Netstandard13.Tests/EventSourceTelemetryModuleTests.cs
- src/Adapters.Tests/Shared/CustomTelemetryChannel.cs
- src/Adapters/Etw.Net451/EtwTelemetryModule.cs
- src/Adapters/EventSource.Netstandard13/EventSourceTelemetryModule.cs
- src/Adapters/EventSource.Shared/EventSource.Shared/EventSource.Shared.projitems
- src/Adapters/EventSource.Shared/EventSource.Shared/Utilities/TplActivities.cs
The problem was found by EventFlow users, this change is a port of the fix from that library.
Basically, we want the TPL EventSource to be enabled as it provides hierarchical activity IDs. But the events emitted from that EventSource are not very useful, at least not during production tracing, so we want them disabled. Examples of events emitted by this source are "task X started task Y", "task X resumed after waiting on tasks Y and Z" and similar.
We could consider disabling the events only if they are not explicitly requested by the telemetry module configuration, but I doubt users will be interested in TPL events in the APM context.
> Suppress TPL events for EventSource and ETW modules

- src/Adapters.Tests/Log4NetAppender.Tests.Shared/ApplicationInsightsAppenderTests.cs
- src/Adapters.Tests/NLogTarget.Tests.Shared/NLogTargetTests.cs
- src/Adapters.Tests/TraceListener.Tests.Shared/ApplicationInsightsTraceListenerTests.cs
Opened #112  to return the tests back.
Currently, they should be disabled to unblock PR merges into develop.
> Ignore Ednpoint Validation Tests

- src/Adapters.Tests/EventSource.Netstandard13.Tests/EventSourceTelemetryModuleTests.cs
- src/Adapters/EventSource.Netstandard13/EventSourceTelemetryModule.cs
- src/Adapters/EventSource.Netstandard13/Implementation/EventDataExtensions.cs
- src/Adapters/EventSource.Shared/EventSource.Shared/Implementation/EventSourceListenerEventSource.cs
We use Tracelogging extensively in our system and we often log nested EventData objects via Write<T>. The current implementation doesn't work for this scenario since it just calls ToString() on each value in the Payload collection. This change allows for implementing your own handler for converting EventWrittenEventArgs to TraceTelemetry.
> Extensible payload handler

- CHANGELOG.md
- src/NLogTarget/NLogTarget.csproj
- test/NLogTarget.Net45.Tests/NLogTarget.Net45.Tests.csproj
sdl has recommended but not required that we upgrade our version of NLog.
This is a trivial non-breaking change, no real reason not to do it.
This will not change the min-required version (4.3.8).
I ran all tests and they continue to pass.
> sdl upgrade NLog

- Logging.sln
- src/DiagnosticSourceListener/DiagnosticSourceListenerSubscription.cs
- test/DiagnosticSourceListener.netcoreapp10.Tests/DiagnosticSourceTelemetryModuleTests.cs
The DiagnosticSourceListener tests project got removed with the last round of project shuffling (#135)
This puts it back.
Also fix a bug (NRE) when property values are null and add a test to cover that case.
> Fix NRE in DiagnosticSourceListener when property values are null

- GlobalStaticVersion.props
Fix for failed builds.
"C:\Repos\SDK\ApplicationInsights-dotnet\dirs.proj" (default target) (1) ->
"C:\Repos\SDK\ApplicationInsights-dotnet\Microsoft.ApplicationInsights.sln" (Restore;Build target) (2) ->
(Restore target) ->
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.tar
gets(103,5): **error : '2.5.0-' is not a valid version string.** [C:\Repos\SDK\ApplicationInsights-dotnet\Microsoft.Applica
tionInsights.sln]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targe
ts(103,5): error : Parameter name: value [C:\Repos\SDK\ApplicationInsights-dotnet\Microsoft.ApplicationInsights.sln]
> fix for msbuild fail

- src/NLogTarget/ApplicationInsightsTarget.cs
- test/NLogTarget.Net45.Tests/NLogTargetTests.cs
Nlog has a Global Diagnostics Context dictionary for app-wide
instance values (ref https://github.com/NLog/NLog/wiki/Gdc-layout-renderer).
Include these in the properties sent to the NLog target.
> Add NLog GlobalDiagnosticContext properties.

- CHANGELOG.md
- Logging.sln
- src/Log4NetAppender/ApplicationInsightsAppender.cs
- test/Log4NetAppender.Net45.Tests/ApplicationInsightsAppenderTests.cs
Remove UserId from Log4Net. Update test and changelog.
#153
> remove autocollection of userId from Log4Net

- test/Log4NetAppender.Net45.Tests/ApplicationInsightsAppenderTests.cs
- test/Shared/AdapterHelper.cs
- test/Shared/ApplicationInsightsTraceListenerTests.cs
Fixes #173 
I reverted my changes to AdapterHelper. The key thing is NOT to set TelemetryConfiguration.Active.InstrumentationKey there. 
That fixed the failing EventSourceTelemetryModule test. To be honest, I have no idea why.
However, it broke two others. So I fixed those by manually setting TelemetryConfiguration.Active.InstrumentationKey.
> Fix failing unit tests

- CHANGELOG.md
- src/NLogTarget/ApplicationInsightsTarget.cs
But only when something to flush. Partially resolves #177 for NLog (Probably also an issue for all other logging destinations)
> NLog ApplicationInsightsTarget Flush with async delay

- src/DiagnosticSourceListener/DiagnosticSourceTelemetryModule.cs
- test/DiagnosticSourceListener.netcoreapp10.Tests/DiagnosticSourceTelemetryModuleTests.cs
Prevent double telemetry if DiagnosticSourceTelemetryModule is initialied twice.
Fixes https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/653
> Prevent double telemetry if DiagnosticSourceTelemetryModule is initialized twice

- src/DiagnosticSourceListener/DiagnosticSourceListeningRequest.cs
- src/EtwCollector/AITraceEventSession.cs
- src/EventSource.Shared/EventSource.Shared/Implementation/EventSourceListenerEventSource.cs
- src/EventSourceListener/EventSourceListeningRequestBase.cs
- src/EventSourceListener/EventSourceTelemetryModule.cs
- src/NLogTarget/ApplicationInsightsTarget.cs
- src/TraceListener/ApplicationInsightsTraceListener.cs
- test/CommonTestShared/SdkVersionHelper.cs
- test/CommonTestShared/TelemetrySender.cs
- test/DiagnosticSourceListener.netcoreapp10.Tests/DiagnosticSourceTelemetryModuleTests.cs
- test/EtwCollector.Net451.Tests/EtwTelemetryModuleTests.cs
- test/EtwCollector.Net451.Tests/EventSourceModuleDiagnosticListener.cs
- test/EtwCollector.Net451.Tests/TraceEventSessionMock.cs
- test/EtwCollector.Net451.Tests/TraceTelemetryComparer.cs
- test/EventSourceListener.netcoreapp10.Tests/EventSourceModuleDiagnosticListener.cs
- test/EventSourceListener.netcoreapp10.Tests/EventSourceTelemetryModuleTests.cs
- test/EventSourceListener.netcoreapp10.Tests/TraceTelemetryComparer.cs
- test/Log4NetAppender.Net45.Tests/ApplicationInsightsAppenderTests.cs
- test/NLogTarget.Net45.Tests/NLogTargetTests.cs
- test/Shared/AdapterHelper.cs
- test/Shared/ApplicationInsightsTraceListenerTests.cs
- test/Shared/CustomTelemetryChannel.cs
CA1307 Use StringComparison.Ordinal for StartsWith
CA1063 Seal classes with trivial Dispose methods
CA1305 Use InvariantCulture for ToString and string.Format
CA1309 Use ordinal comparison
CA1507 Use nameof
CA1801 Review unused parameters
CA1823 Remove unused fields
CA1825 Avoid zero length array allocations
CA2007 Call ConfigureAwait
> Fix FxCop violations

- src/DiagnosticSourceListener/DiagnosticSourceListener.csproj
- src/EtwCollector/EtwCollector.csproj
- src/EventSourceListener/EventSourceListener.csproj
- src/Log4NetAppender/Log4NetAppender.csproj
- src/NLogTarget/NLogTarget.csproj
- src/TraceListener/TraceListener.csproj
Symbols packages had to be disabled due to a bug in our build infrastructure.
That bug has been resolved and we are re-enabling this.
> re-enable symbols packages

- CHANGELOG.md
- src/NLogTarget/ApplicationInsightsTarget.cs
- test/NLogTarget.Net45.Tests/NLogTargetTests.cs
Resolves #201
Normally NLog properties are just added like this:
`public NLog.Layouts.Layout InstrumentationKey { get; set; }`
But because it would be a breaking change, then this PR is a little convoluted.
> NLog ApplicationInsightsTarget - Add support for using GDC for InstrumentationKey

- CHANGELOG.md
- src/EventSourceListener/EventSourceListeningRequestBase.cs
- src/EventSourceListener/EventSourceTelemetryModule.cs
- test/EventSourceListener.netcoreapp10.Tests/EventSourceTelemetryModuleTests.cs
Because of https://github.com/dotnet/coreclr/issues/14434 using EventSourceTelemetryModule might cause an infinite loop. This change prevents it from happening in the case of Micrsoft-ApplicationInsights-Data EventSource. 
The approach has been discussed with @SergeyKanzhelev and @mmilirud
> Disable Microsoft-ApplicationInsights-Data EventSource by default

- Common.props
- GlobalStaticVersion.props
- src/DiagnosticSourceListener/DiagnosticSourceListener.csproj
- src/EtwCollector/EtwCollector.csproj
- src/EventSource.Shared/EventSource.Shared/Implementation/EventSourceListenerEventSource.cs
- src/EventSourceListener/EventSourceListener.csproj
- src/EventSourceListener/EventSourceTelemetryModule.cs
- src/Log4NetAppender/ApplicationInsightsAppender.cs
- src/Log4NetAppender/Log4NetAppender.csproj
- src/NLogTarget/ApplicationInsightsTarget.cs
- src/NLogTarget/NLogTarget.csproj
- src/TraceListener/ApplicationInsightsTraceListener.cs
- src/TraceListener/TraceListener.csproj
Add the FxCop Analyzer to Non-Test projects.
This analyzer identifies **SEVERAL** compiler errors. 
If you're bored one afternoon, feel free to pull this branch and fix a couple! :)
> add fxcop analyzer

- CHANGELOG.md
- src/Log4NetAppender/Log4NetAppender.csproj
- test/Log4NetAppender.Net45.Tests/Log4NetAppender.Net45.Tests.csproj
[Log4Net 2.0.6](https://www.nuget.org/packages/log4net/2.0.6) does not have dependencies specified for .NET 4.6 and it makes Visual Studio Package Manager installing all .NET Standard dependencies instead. This leads to a conflict between .Net and .Net Standard libraries and compilation fails to resolve which of the conflicting assemblies to use.
Starting [Log4net 2.0.7](https://www.nuget.org/packages/log4net/2.0.7), there is an explicit empty list of dependencies for .NET 4.6 and Package Manager does not install any dependencies.
Given that 2.0.6 is downloaded ~190 000 times and 2.0.7 + 2.0.8 are at 8 000 000 downloads, I assume it's safe to update the references from 2.0.6 to 2.0.7.
> UpdateLog4Net to >=2.0.7

- Common.props
- src/EtwCollector/EtwCollector.csproj
- src/EventSourceListener/EventSourceListener.csproj
- src/Log4NetAppender/Log4NetAppender.csproj
- src/NLogTarget/NLogTarget.csproj
- src/TraceListener/TraceListener.csproj
In https://github.com/Microsoft/ApplicationInsights-dotnet-logging/pull/239 new ILogger was introduced that targets netstandard 2.0 and build fails because of code analyzers 
```
CA0055 : Could not identify platform for 'E:\A\_work\107\bin\Release\src\ILogger\netstandard2.0\Microsoft.Extensions.Logging.ApplicationInsights.dll'.
CA0052 : No targets were selected
```
https://stackoverflow.com/questions/46617261/enabling-code-analysis-for-net-core-2-0-project-results-ca0055-and-ca0052-error
> This error is caused by using an old version of Code Analysis with .NET Core. This old version is only for non-.NET Core applications.
The solution is to disable the old Code Analysis for .NET Core projects and install the new version of Code Analysis, which is now a NuGet package. (The reason you …
> Fix fxcop running on netstandard2.0 and failing

- Logging.sln
- src/ILogger/ApplicationInsightsLogger.cs
- src/ILogger/ApplicationInsightsLoggerExtensions.cs
- src/ILogger/ApplicationInsightsLoggerOptions.cs
- src/ILogger/ApplicationInsightsLoggerProvider.cs
- src/ILogger/ApplicationInsightsLoggingBuilderExtensions.cs
- src/ILogger/ILogger.csproj
- src/ILogger/NullScope.cs
- test/ILogger.NetStandard.Tests/ILogger.NetStandard.Tests.csproj
- test/ILogger.NetStandard.Tests/ILoggerIntegrationTests.cs
- test/ILogger.NetStandard.Tests/TestTelemetryProcessor.cs
Original discussion at -  https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/749
Packages installed 
```xml
<ItemGroup>
<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="2.1.0" />
<PackageReference Include="Microsoft.Extensions.Logging" Version="2.1.0" />
<PackageReference Include="Microsoft.Extensions.Logging.ApplicationInsights" Version="2.8.1-build39946" />
<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="2.1.0" />
</ItemGroup>
```
```cs
class Program
{
static void Main(string[] args)
{
// Create DI container.
IServiceCollection services = new ServiceCollection();
// Add the logging pipelines to use. We are using Console and AI and configuring them both.
services.AddLogging(loggingBuilder =>
{ …
```
> ILogger implementation for ApplicationInsights

- GlobalStaticVersion.props
fixes test issue 
```
2018-12-31T21:18:18.4956638Z Failed   SdkVersionIsCorrect
2018-12-31T21:18:18.4957159Z Error Message:
2018-12-31T21:18:18.4957400Z  Assert.AreEqual failed. Expected:<sd:2.9.0-43936>. Actual:<sd:2.9.0-43935>. 
2018-12-31T21:18:18.4957473Z Stack Trace:
2018-12-31T21:18:18.4957574Z    at Microsoft.ApplicationInsights.TraceListener.Tests.ApplicationInsightsTraceListenerTests.SdkVersionIsCorrect() in E:\A\_work\182\s\test\Shared\ApplicationInsightsTraceListenerTests.cs:line 107
2018-12-31T21:18:18.4957662Z 
```
https://dev.azure.com/mseng/AppInsights/_build/results?buildId=8103125
> Update semantic version

- test/CommonTestShared/SdkVersionHelper.cs
- test/DiagnosticSourceListener.netcoreapp10.Tests/DiagnosticSourceTelemetryModuleTests.cs
- test/EventSourceListener.netcoreapp10.Tests/EventSourceTelemetryModuleTests.cs
- test/Log4NetAppender.Net45.Tests/ApplicationInsightsAppenderTests.cs
- test/NLogTarget.Net45.Tests/NLogTargetTests.cs
- test/Shared/ApplicationInsightsTraceListenerTests.cs
There is no point in comparing the version of test assembly with the version of logging assembly - they don't have to match. It causes random test failures.
This change calculates SDK internal version based on the real assembly version rather than test one.
> Fix version comparison tests

- NuGet.Config
Otherwise it's not possible to test/build logging with appinsights that is not on nuget yet.
> Add myget feed to nuget.config

- CHANGELOG.md
- GlobalStaticVersion.props
- NugetAudit.ps1
- src/DiagnosticSourceListener/DiagnosticSourceListener.csproj
- src/EtwCollector/EtwCollector.csproj
- src/EventSourceListener/EventSourceListener.csproj
- src/ILogger/ILogger.csproj
- src/Log4NetAppender/Log4NetAppender.csproj
- src/NLogTarget/NLogTarget.csproj
- src/Product.props
- src/TraceListener/TraceListener.csproj
- test/DiagnosticSourceListener.netcoreapp10.Tests/DiagnosticSourceListener.netcoreapp1.Tests.csproj
- test/EtwCollector.Net451.Tests/EtwCollector.Net451.Tests.csproj
- test/EventSourceListener.netcoreapp10.Tests/EventSourceListener.netcoreapp10.Tests.csproj
- test/Log4NetAppender.Net45.Tests/Log4NetAppender.Net45.Tests.csproj
- test/Log4NetAppender.NetCoreApp10.Tests/Log4NetAppender.NetCoreApp10.Tests.csproj
- test/NLogTarget.Net45.Tests/NLogTarget.Net45.Tests.csproj
- test/NLogTarget.NetCoreApp10.Tests/NLogTarget.NetCoreApp10.Tests.csproj
- test/TraceListener.Net45.Tests/TraceListener.Net45.Tests.csproj
- test/TraceListener.netcoreapp10.Tests/TraceListener.netcoreapp10.Tests.csproj
- test/Xdt.Tests/Xdt.Tests.csproj
Preparing stable in develop - it looks like we can take all commits into master.
@cijothomas , PR for ILogger #239 was part of Beta3 for ~4 weeks now, it looks like it can be a part of the stable, is that correct?
> Update to Base SDK 2.9.0

- CHANGELOG.md
- GlobalStaticVersion.props
- src/DiagnosticSourceListener/DiagnosticSourceListener.csproj
- src/EtwCollector/EtwCollector.csproj
- src/EventSourceListener/EventSourceListener.csproj
- src/EventSourceListener/Properties/AssemblyInfo.cs
- src/ILogger/ApplicationInsightsLogger.cs
- src/ILogger/ILogger.csproj
- src/Log4NetAppender/Log4NetAppender.csproj
- src/NLogTarget/NLogTarget.csproj
- src/TraceListener/TraceListener.csproj
- test/DiagnosticSourceListener.netcoreapp10.Tests/DiagnosticSourceListener.netcoreapp1.Tests.csproj
- test/EtwCollector.Net451.Tests/EtwCollector.Net451.Tests.csproj
- test/EventSourceListener.netcoreapp10.Tests/EventSourceListener.netcoreapp10.Tests.csproj
- test/ILogger.NetStandard.Tests/ILoggerIntegrationTests.cs
- test/Log4NetAppender.Net45.Tests/Log4NetAppender.Net45.Tests.csproj
- test/Log4NetAppender.NetCoreApp10.Tests/Log4NetAppender.NetCoreApp10.Tests.csproj
- test/NLogTarget.Net45.Tests/NLogTarget.Net45.Tests.csproj
- test/NLogTarget.NetCoreApp10.Tests/NLogTarget.NetCoreApp10.Tests.csproj
- test/TraceListener.Net45.Tests/TraceListener.Net45.Tests.csproj
- test/TraceListener.netcoreapp10.Tests/TraceListener.netcoreapp10.Tests.csproj
- test/Xdt.Tests/Xdt.Tests.csproj
ILogger - If an exception is passed to log, then Exception.Message is populated as ExceptionTelemetry.Message. 
If TrackExceptionsAsExceptionTelemetry is false, then Exception.Message is stored as custom property "ExceptionMessage"
Foe example, consider the following log call.
testLogger.LogError(new Exception("ExceptionMessage"), "LoggerMessage");
The ExceptionTelemetry created will contain "ExceptionMessage" in its Message field. "LoggerMessage" will be in custom property "FormattedMessage"
If TrackExceptionsAsExceptionTelemetry is false, then TraceTelemetry is created, and "LoggerMessage" will be in its Message field. "ExceptionMessage" will be in custom property "ExceptionMessage"
Prior to this, when an exception is passed to log, its Exception.Message was not stored anywhere.
Also …
> ILogger - Exception.Message is populated as ExceptionTelemetry.Message, Bump version

- CHANGELOG.md
- src/DiagnosticSourceListener/DiagnosticSourceListener.csproj
- src/EtwCollector/EtwCollector.csproj
- src/EventSourceListener/EventSourceListener.csproj
- src/ILogger/ILogger.csproj
- src/Log4NetAppender/Log4NetAppender.csproj
- src/NLogTarget/NLogTarget.csproj
- src/TraceListener/TraceListener.csproj
- test/DiagnosticSourceListener.netcoreapp10.Tests/DiagnosticSourceListener.netcoreapp1.Tests.csproj
- test/EtwCollector.Net451.Tests/EtwCollector.Net451.Tests.csproj
- test/EventSourceListener.netcoreapp10.Tests/EventSourceListener.netcoreapp10.Tests.csproj
- test/Log4NetAppender.Net45.Tests/Log4NetAppender.Net45.Tests.csproj
- test/Log4NetAppender.NetCoreApp10.Tests/Log4NetAppender.NetCoreApp10.Tests.csproj
- test/NLogTarget.Net45.Tests/NLogTarget.Net45.Tests.csproj
- test/NLogTarget.NetCoreApp10.Tests/NLogTarget.NetCoreApp10.Tests.csproj
- test/TraceListener.Net45.Tests/TraceListener.Net45.Tests.csproj
- test/TraceListener.netcoreapp10.Tests/TraceListener.netcoreapp10.Tests.csproj
- test/Xdt.Tests/Xdt.Tests.csproj
also updated DiagnosticSource to stay in sync with BaseSDK https://github.com/microsoft/ApplicationInsights-dotnet/pull/1183
> bump version 2.11-beta2
