CHANGELOG.md
GlobalStaticVersion.props
src/Adapters.Tests/TraceListener.Tests.Shared/ApplicationInsightsTraceListenerTests.cs
src/Adapters/TraceListener.Shared/ApplicationInsightsTraceListener.cs

Fix: EventId is always 0

---

CHANGELOG.md
src/Adapters.Tests/Log4NetAppender.Tests.Shared/ApplicationInsightsAppenderTests.cs
src/Adapters.Tests/NLogTarget.Tests.Shared/NLogTargetTests.cs
src/Adapters.Tests/TraceListener.Tests.Shared/ApplicationInsightsTraceListenerTests.cs
src/Adapters/Log4NetAppender.Shared/ApplicationInsightsAppender.cs
src/Adapters/NLogTarget.Shared/ApplicationInsightsTarget.cs
src/Adapters/TraceListener.Shared/ApplicationInsightsTraceListener.cs

Changing properties collection (Issues 3,5,7)

---

src/Adapters.Tests/NLogTarget.Tests.Shared/NLogTargetTests.cs
src/Adapters/NLogTarget.Shared/ApplicationInsightsTarget.cs

Add layout support

---

src/Adapters.Tests/NLogTarget.Tests.Shared/NLogTargetTests.cs
src/Adapters/NLogTarget.Shared/ApplicationInsightsTarget.cs

Possible fix for issue 29.  Now with working comparisons!

Possible fix for issue 29

---

src/Adapters.Tests/EventSource.Netstandard13.Tests/EventSource.Netstandard13.Tests.csproj
src/Adapters/EventSource.Netstandard13/EventSource.Netstandard13.csproj

Third time is the charm as they say...

Update MS.AI reference

---

Logging.sln
src/Adapters.Tests/DiagnosticSource.Tests/DiagnosticSource.Tests.csproj
src/Adapters.Tests/DiagnosticSource.Tests/DiagnosticSourceTelemetryModuleTests.cs
src/Adapters.Tests/DiagnosticSource.Tests/TestDiagnosticSource.cs
src/Adapters/DiagnosticSource/DeclaredPropertiesCache.cs
src/Adapters/DiagnosticSource/DiagnosticSource.csproj
src/Adapters/DiagnosticSource/DiagnosticSourceListenerSubscription.cs
src/Adapters/DiagnosticSource/DiagnosticSourceListeningRequest.cs
src/Adapters/DiagnosticSource/DiagnosticSourceTelemetryModule.cs
src/NuGet.Tests/Xdt.Tests/Resources/DiagnosticSourceListener/TestDataSet.xml
src/NuGet.Tests/Xdt.Tests/Xdt.Tests.csproj
src/NuGet.Tests/Xdt.Tests/XdtTests.cs
src/NuGet/DiagnosticSourceListener/ApplicationInsights.config.install.xdt
src/NuGet/DiagnosticSourceListener/ApplicationInsights.config.uninstall.xdt
src/NuGet/DiagnosticSourceListener/DiagnosticSourceListener.NuGet.csproj
src/NuGet/DiagnosticSourceListener/Package.nuspec
src/NuGet/DiagnosticSourceListener/build/Microsoft.ApplicationInsights.DiagnosticSourceListener.targets

Introduce DiagnosticSourceListener

---

src/NuGet/EventSourceListener/EventSourceListener.NuGet.csproj

Fix build break

---

src/Adapters.Tests/DiagnosticSource.Tests/DiagnosticSource.Tests.csproj
src/Adapters/DiagnosticSource/DiagnosticSource.csproj

Reference v2.3 of AI base SDK in DiagnosticSourceListener

---

src/Adapters.Tests/EventSource.Netstandard13.Tests/EventSourceTelemetryModuleTests.cs
src/Adapters.Tests/EventSource.Netstandard13.Tests/OtherTestEventSource.cs
src/Adapters/EventSource.Netstandard13/EventSourceTelemetryModule.cs
src/Adapters/EventSource.Netstandard13/Implementation/EventDataExtensions.cs

The same as #110 . Re-opened to re-run the build.

Fix deadlock in Event Source Telemetry Module

---

src/Adapters/EventSource.Netstandard13/EventSourceTelemetryModule.cs
src/Adapters/EventSource.Netstandard13/Implementation/EventDataExtensions.cs

Fixes some code analysis breaks caused by my previous PR #111

Fix code analysis breaks

---

src/Adapters/EventSource.Netstandard13/Implementation/EventDataExtensions.cs

Rever changes

---

SDL/BinSkimSetup.ps1

BinSkim will fail on our test directories.
This script will copy necessary files to a new directory to be scanned
https://www.microsoft.com/en-us/SDL/adopt/tools.aspx

setup script for running binskim

---

SDL/FxCopSetup.ps1

need to move dependencies for fxcop

sdl script revision

---

src/DiagnosticSourceListener/DiagnosticSourceListenerSubscription.cs
test/DiagnosticSourceListener.netcoreapp10.Tests/DiagnosticSourceTelemetryModuleTests.cs

Fix Code Analysis breaks (CA1305) from #143

Use InvariantCulture to convert property values

---

CHANGELOG.md
GlobalStaticVersion.props

version bump and update changelog

version bump for 2.5.0 release

---

GlobalStaticVersion.props
src/DiagnosticSourceListener/DiagnosticSourceListener.csproj
src/EtwCollector/EtwCollector.csproj
src/EventSourceListener/EventSourceListener.csproj
src/Log4NetAppender/Log4NetAppender.csproj
src/NLogTarget/NLogTarget.csproj
src/TraceListener/TraceListener.csproj
test/DiagnosticSourceListener.netcoreapp10.Tests/DiagnosticSourceListener.netcoreapp1.Tests.csproj
test/EtwCollector.Net451.Tests/EtwCollector.Net451.Tests.csproj
test/EventSourceListener.netcoreapp10.Tests/EventSourceListener.netcoreapp10.Tests.csproj
test/Log4NetAppender.Net45.Tests/Log4NetAppender.Net45.Tests.csproj
test/Log4NetAppender.NetCoreApp10.Tests/Log4NetAppender.NetCoreApp10.Tests.csproj
test/NLogTarget.Net45.Tests/NLogTarget.Net45.Tests.csproj
test/NLogTarget.NetCoreApp10.Tests/NLogTarget.NetCoreApp10.Tests.csproj
test/TraceListener.Net45.Tests/TraceListener.Net45.Tests.csproj
test/TraceListener.netcoreapp10.Tests/TraceListener.netcoreapp10.Tests.csproj
test/Xdt.Tests/Xdt.Tests.csproj

we can wait until BaseSdk and WebSdk go to Nuget, but this is done and ready to ship :)

version bump 2.6.2

---

HelloWorldTest/README.md

add readme

---

AddXmlLanguage.targets
Common.props

Fixes #[853](https://github.com/Microsoft/ApplicationInsights-dotnet/issues/863).

Add Xml Doc back to Nuget Packages

---

ApplicationInsightsSDKRules.ruleset

- disable TaskScheduler warning

fix fxcop warnings

---

Common.props

enable warnings as errors

---

src/Product.props

added azure tag to nugets for discoverability

---

src/ILogger/Readme.md

Microsoft.Extensions.Logging.applicaitonInsights README: Fix indentation and nits

---

src/DiagnosticSourceListener/DiagnosticSourceListener.csproj
src/EtwCollector/EtwCollector.csproj
src/EventSourceListener/EventSourceListener.csproj
src/ILogger/ILogger.csproj
src/Log4NetAppender/Log4NetAppender.csproj
src/NLogTarget/NLogTarget.csproj
src/TraceListener/TraceListener.csproj

MicroBuild in the conditional ItemGroup has been causing problems.
Changing all projects for consistency.

fix signing

---

Logging.sln
Nupkg.props
src/DiagnosticSourceListener/DiagnosticSourceListener.csproj
src/EtwCollector/EtwCollector.csproj
src/EventSourceListener/EventSourceListener.csproj
src/ILogger/ILogger.csproj
src/Log4NetAppender/Log4NetAppender.csproj
src/NLogTarget/NLogTarget.csproj
src/Product.props
src/TraceListener/TraceListener.csproj

https://github.com/microsoft/ApplicationInsights-Home/issues/370

nupkg and symbols
